# netlify.toml
[[headers]]
  for = "/api/*"
  [headers.values]
  Netlify-CDN-Cache-Control = "public, max-age=60"

# Set the build settings
[build]
  publish = "build"  # Directory that Netlify will deploy


# Define custom headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://fonts.googleapis.com; script-src 'self' https://cdn.jsdelivr.net; object-src 'none'; style-src 'self' https://fonts.googleapis.com;"
    X-Frame-Options = "DENY"


# Function settings
[functions]
  directory = "netlify/functions"  # Directory where your Netlify Functions are stored
  node_bundler = "esbuild"  # Optional: Specify the JavaScript bundler (default is "zisi")
